# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release to NuGet
  
on:  
  release:  
    types: [created]  # Trigger the workflow on release creation  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
      
    steps:  
      - uses: actions/checkout@v4  
        with:  
          fetch-depth: 0  # Fetch all history for all branches and tags  
  
      - name: Setup .NET  
        uses: actions/setup-dotnet@v4  
        with:  
          dotnet-version: 8.0.x  
  
      - name: Restore dependencies  
        run: dotnet restore  
  
      - name: Build  
        run: dotnet build --configuration Release --no-restore  
  
      - name: Test  
        run: dotnet test --no-build --verbosity normal  
  
      - name: Get Version from Release Tag  
        id: get_version  
        run: |  
          # Use the GitHub context to get the tag name  
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV  # Strip the refs/tags/ prefix  
  
      - name: Pack  
        run: dotnet pack --configuration Release --output ./nupkgs /p:Version=${{ env.VERSION }} /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg  
  
      - name: Publish to NuGet  
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json  
        env:  
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  
